################################################################################
### This file is automatically generated by spec/bin/generate_type_specs.rb
### It is intended to be human readable (hence being checked into Git), but
### not manually edited.
### This is to make it easier to maintain tests for all supported Postgres
### types, even as extensions or new Postgres versions add new types.
################################################################################

shared_examples 'type specs' do

  describe 'abstime' do
    example('internal type not supported') {}
  end

  describe 'aclitem' do
    pending('should have specs') { fail 'spec not yet implemented' }
  end

  describe 'bigint' do
    include_examples 'numeric type', "bigint"
  end

  describe 'bit' do
    include_examples 'bit-string type', "bit", "1110", 4
  end

  describe 'bit varying' do
    include_examples 'bit-string type', "bit varying"
  end

  describe 'boolean' do
    include_examples 'roundtrip type', "boolean", true
  end

  describe 'box' do
    pending('should have specs') { fail 'spec not yet implemented' }
  end

  describe 'bytea' do
    pending('should have specs') { fail 'spec not yet implemented' }
  end

  describe '"char"' do
    example('internal type not supported') {}
  end

  describe 'character' do
    include_examples 'string type', "character", "Hello", 5
  end

  describe 'character varying' do
    include_examples 'string type', "character varying"
  end

  describe 'cid' do
    pending('should have specs') { fail 'spec not yet implemented' }
  end

  describe 'cidr' do
    pending('should have specs') { fail 'spec not yet implemented' }
  end

  describe 'circle' do
    pending('should have specs') { fail 'spec not yet implemented' }
  end

  describe 'date' do
    include_examples "date"
  end

  describe 'daterange' do
    pending('should have specs') { fail 'spec not yet implemented' }
  end

  describe 'double precision' do
    include_examples 'numeric type', "double precision"
  end

  describe 'gtsvector' do
    pending('should have specs') { fail 'spec not yet implemented' }
  end

  describe 'inet' do
    pending('should have specs') { fail 'spec not yet implemented' }
  end

  describe 'int2vector' do
    pending('should have specs') { fail 'spec not yet implemented' }
  end

  describe 'int4range' do
    pending('should have specs') { fail 'spec not yet implemented' }
  end

  describe 'int8range' do
    pending('should have specs') { fail 'spec not yet implemented' }
  end

  describe 'integer' do
    include_examples 'numeric type', "integer"
  end

  describe 'interval' do
    pending('should have specs') { fail 'spec not yet implemented' }
  end

  describe 'json' do
    pending('should have specs') { fail 'spec not yet implemented' }
  end

  describe 'jsonb' do
    pending('should have specs') { fail 'spec not yet implemented' }
  end

  describe 'line' do
    pending('should have specs') { fail 'spec not yet implemented' }
  end

  describe 'lseg' do
    pending('should have specs') { fail 'spec not yet implemented' }
  end

  describe 'macaddr' do
    pending('should have specs') { fail 'spec not yet implemented' }
  end

  describe 'money' do
    include_examples 'numeric type', "money"
  end

  describe 'name' do
    example('internal type not supported') {}
  end

  describe 'numeric' do
    before :example do
      known_bug "replaced by zero", "https://github.com/confluentinc/bottledwater-pg/issues/4"
    end

    include_examples 'numeric type', "numeric"
  end

  describe 'numrange' do
    pending('should have specs') { fail 'spec not yet implemented' }
  end

  describe 'oid' do
    include_examples 'numeric type', "oid"
  end

  describe 'oidvector' do
    pending('should have specs') { fail 'spec not yet implemented' }
  end

  describe 'path' do
    pending('should have specs') { fail 'spec not yet implemented' }
  end

  describe 'pg_lsn' do
    pending('should have specs') { fail 'spec not yet implemented' }
  end

  describe 'pg_node_tree' do
    example('internal type not supported') {}
  end

  describe 'point' do
    pending('should have specs') { fail 'spec not yet implemented' }
  end

  describe 'polygon' do
    pending('should have specs') { fail 'spec not yet implemented' }
  end

  describe 'real' do
    include_examples 'numeric type', "real"
  end

  describe 'refcursor' do
    pending('should have specs') { fail 'spec not yet implemented' }
  end

  describe 'regclass' do
    example('internal type not supported') {}
  end

  describe 'regconfig' do
    example('internal type not supported') {}
  end

  describe 'regdictionary' do
    example('internal type not supported') {}
  end

  describe 'regoper' do
    example('internal type not supported') {}
  end

  describe 'regoperator' do
    example('internal type not supported') {}
  end

  describe 'regproc' do
    example('internal type not supported') {}
  end

  describe 'regprocedure' do
    example('internal type not supported') {}
  end

  describe 'regtype' do
    example('internal type not supported') {}
  end

  describe 'reltime' do
    example('internal type not supported') {}
  end

  describe 'smallint' do
    include_examples 'numeric type', "smallint"
  end

  describe 'smgr' do
    pending('should have specs') { fail 'spec not yet implemented' }
  end

  describe 'text' do
    include_examples 'string type', "text"
  end

  describe 'tid' do
    pending('should have specs') { fail 'spec not yet implemented' }
  end

  describe 'timestamp without time zone' do
    include_examples "timestamp without time zone"
  end

  describe 'timestamp with time zone' do
    include_examples "timestamp with time zone"
  end

  describe 'time without time zone' do
    include_examples "time without time zone"
  end

  describe 'time with time zone' do
    include_examples "time with time zone"
  end

  describe 'tinterval' do
    pending('should have specs') { fail 'spec not yet implemented' }
  end

  describe 'tsquery' do
    pending('should have specs') { fail 'spec not yet implemented' }
  end

  describe 'tsrange' do
    pending('should have specs') { fail 'spec not yet implemented' }
  end

  describe 'tstzrange' do
    pending('should have specs') { fail 'spec not yet implemented' }
  end

  describe 'tsvector' do
    pending('should have specs') { fail 'spec not yet implemented' }
  end

  describe 'txid_snapshot' do
    example('internal type not supported') {}
  end

  describe 'unknown' do
    example('internal type not supported') {}
  end

  describe 'uuid' do
    pending('should have specs') { fail 'spec not yet implemented' }
  end

  describe 'xid' do
    example('internal type not supported') {}
  end

  describe 'xml' do
    pending('should have specs') { fail 'spec not yet implemented' }
  end

end
