################################################################################
### This file is automatically generated by spec/bin/generate_type_specs.rb
### It is intended to be human readable (hence being checked into Git), but
### not manually edited.
### This is to make it easier to maintain tests for all supported Postgres
### types, even as extensions or new Postgres versions add new types.
################################################################################

# Arbitrary datetime to test with: first commit to Bottled Water (per Git)
# (plus invented fractional seconds to test roundtrip fidelity)
TEST_DATETIME = Time.new(2014, 12, 27, 17, 40, 15.123456, '+01:00')

shared_examples 'type specs' do

  describe 'abstime' do
    example('internal type not supported') {}
  end

  describe 'aclitem' do
    pending('should have specs') { fail 'spec not yet implemented' }
  end

  describe 'bigint' do
    include_examples 'numeric type', "bigint", 42
  end

  describe 'bit' do
    include_examples 'bit-string type', "bit", "1110", length: 4
  end

  describe 'bit varying' do
    include_examples 'bit-string type', "bit varying"
  end

  describe 'boolean' do
    include_examples 'roundtrip type', "boolean", true
  end

  describe 'box' do
    pending('should have specs') { fail 'spec not yet implemented' }
  end

  describe 'bytea' do
    pending('should have specs') { fail 'spec not yet implemented' }
  end

  describe '"char"' do
    example('internal type not supported') {}
  end

  describe 'character' do
    include_examples 'string type', "character", "Hello", length: 5
  end

  describe 'character varying' do
    include_examples 'string type', "character varying", "Hello, world!"
  end

  describe 'cid' do
    pending('should have specs') { fail 'spec not yet implemented' }
  end

  describe 'cidr' do
    include_examples 'roundtrip type', "cidr", "192.168.1.0/24"
  end

  describe 'circle' do
    pending('should have specs') { fail 'spec not yet implemented' }
  end

  describe 'date' do
    include_examples "date", TEST_DATETIME.to_date
  end

  describe 'daterange' do
    pending('should have specs') { fail 'spec not yet implemented' }
  end

  describe 'double precision' do
    include_examples 'numeric type', "double precision", 42
  end

  describe 'gtsvector' do
    pending('should have specs') { fail 'spec not yet implemented' }
  end

  describe 'inet' do
    include_examples 'roundtrip type', "inet", "192.168.1.1/24"
  end

  describe 'int2vector' do
    pending('should have specs') { fail 'spec not yet implemented' }
  end

  describe 'int4range' do
    pending('should have specs') { fail 'spec not yet implemented' }
  end

  describe 'int8range' do
    pending('should have specs') { fail 'spec not yet implemented' }
  end

  describe 'integer' do
    include_examples 'numeric type', "integer", 42
  end

  describe 'interval' do
    pending('should have specs') { fail 'spec not yet implemented' }
  end

  describe 'json' do
    pending('should have specs') { fail 'spec not yet implemented' }
  end

  describe 'jsonb' do
    pending('should have specs') { fail 'spec not yet implemented' }
  end

  describe 'line' do
    pending('should have specs') { fail 'spec not yet implemented' }
  end

  describe 'lseg' do
    pending('should have specs') { fail 'spec not yet implemented' }
  end

  describe 'macaddr' do
    pending('should have specs') { fail 'spec not yet implemented' }
  end

  describe 'money' do
    before :example do
      xbug "mysteriously gets multiplied by 100"
    end

    include_examples 'numeric type', "money", 42
  end

  describe 'name' do
    example('internal type not supported') {}
  end

  describe 'numeric' do
    before :example do
      known_bug "replaced by zero", "https://github.com/confluentinc/bottledwater-pg/issues/4"
    end

    include_examples 'numeric type', "numeric", 42
  end

  describe 'numrange' do
    pending('should have specs') { fail 'spec not yet implemented' }
  end

  describe 'oid' do
    include_examples 'numeric type', "oid", 42
  end

  describe 'oidvector' do
    pending('should have specs') { fail 'spec not yet implemented' }
  end

  describe 'path' do
    pending('should have specs') { fail 'spec not yet implemented' }
  end

  describe 'pg_lsn' do
    pending('should have specs') { fail 'spec not yet implemented' }
  end

  describe 'pg_node_tree' do
    example('internal type not supported') {}
  end

  describe 'point' do
    pending('should have specs') { fail 'spec not yet implemented' }
  end

  describe 'polygon' do
    pending('should have specs') { fail 'spec not yet implemented' }
  end

  describe 'real' do
    include_examples 'numeric type', "real", 42
  end

  describe 'refcursor' do
    pending('should have specs') { fail 'spec not yet implemented' }
  end

  describe 'regclass' do
    example('internal type not supported') {}
  end

  describe 'regconfig' do
    example('internal type not supported') {}
  end

  describe 'regdictionary' do
    example('internal type not supported') {}
  end

  describe 'regoper' do
    example('internal type not supported') {}
  end

  describe 'regoperator' do
    example('internal type not supported') {}
  end

  describe 'regproc' do
    example('internal type not supported') {}
  end

  describe 'regprocedure' do
    example('internal type not supported') {}
  end

  describe 'regtype' do
    example('internal type not supported') {}
  end

  describe 'reltime' do
    example('internal type not supported') {}
  end

  describe 'smallint' do
    include_examples 'numeric type', "smallint", 42
  end

  describe 'smgr' do
    pending('should have specs') { fail 'spec not yet implemented' }
  end

  describe 'text' do
    include_examples 'string type', "text", "Hello, world!"
  end

  describe 'tid' do
    pending('should have specs') { fail 'spec not yet implemented' }
  end

  describe 'timestamp without time zone' do
    include_examples "timestamp without time zone", TEST_DATETIME
  end

  describe 'timestamp with time zone' do
    include_examples "timestamp with time zone", TEST_DATETIME
  end

  describe 'time without time zone' do
    include_examples "time without time zone", TEST_DATETIME
  end

  describe 'time with time zone' do
    include_examples "time with time zone", TEST_DATETIME
  end

  describe 'tinterval' do
    pending('should have specs') { fail 'spec not yet implemented' }
  end

  describe 'tsquery' do
    pending('should have specs') { fail 'spec not yet implemented' }
  end

  describe 'tsrange' do
    pending('should have specs') { fail 'spec not yet implemented' }
  end

  describe 'tstzrange' do
    pending('should have specs') { fail 'spec not yet implemented' }
  end

  describe 'tsvector' do
    pending('should have specs') { fail 'spec not yet implemented' }
  end

  describe 'txid_snapshot' do
    example('internal type not supported') {}
  end

  describe 'unknown' do
    example('internal type not supported') {}
  end

  describe 'uuid' do
    pending('should have specs') { fail 'spec not yet implemented' }
  end

  describe 'xid' do
    example('internal type not supported') {}
  end

  describe 'xml' do
    pending('should have specs') { fail 'spec not yet implemented' }
  end

end
